"""mailman filter id replaces trigger id

Revision ID: 894c633d1be3
Revises: 971f7697ff08
Create Date: 2026-07-22 09:50:39.218565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894c633d1be3'
down_revision: Union[str, None] = '971f7697ff08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailman_settings', sa.Column('gmail_filter_id', sa.String(length=128), nullable=True))
    op.drop_column('mailman_settings', 'composio_trigger_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailman_settings', sa.Column('composio_trigger_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('mailman_settings', 'gmail_filter_id')
    # ### end Alembic commands ###
