"""add interval_minutes to mailman_settings

Revision ID: 971f7697ff08
Revises: c20b28cd5d0a
Create Date: 2026-07-22 09:39:58.230741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971f7697ff08'
down_revision: Union[str, None] = 'c20b28cd5d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailman_settings', sa.Column('interval_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailman_settings', 'interval_minutes')
    # ### end Alembic commands ###
