"""add categorization tables

Revision ID: bb9e0a302824
Revises: 2bd3ef053b8b
Create Date: 2026-07-27 10:49:23.570686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb9e0a302824'
down_revision: Union[str, None] = '2bd3ef053b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorization_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('match_value', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('category_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorization_rules_priority'), 'categorization_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_categorization_rules_user_id'), 'categorization_rules', ['user_id'], unique=False)
    op.create_table('categorization_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('fallback_category_key', sa.String(length=64), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('extra_instructions', sa.Text(), nullable=True),
    sa.Column('last_reclassify_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorization_settings_user_id'), 'categorization_settings', ['user_id'], unique=True)
    op.create_table('email_categories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('gmail_label', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color_bg', sa.String(length=7), nullable=False),
    sa.Column('color_text', sa.String(length=7), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_email_categories_user_key')
    )
    op.create_index(op.f('ix_email_categories_user_id'), 'email_categories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_categories_user_id'), table_name='email_categories')
    op.drop_table('email_categories')
    op.drop_index(op.f('ix_categorization_settings_user_id'), table_name='categorization_settings')
    op.drop_table('categorization_settings')
    op.drop_index(op.f('ix_categorization_rules_user_id'), table_name='categorization_rules')
    op.drop_index(op.f('ix_categorization_rules_priority'), table_name='categorization_rules')
    op.drop_table('categorization_rules')
    # ### end Alembic commands ###
