"""mailman settings, vip rules, held emails

Revision ID: c20b28cd5d0a
Revises: 734b495994a8
Create Date: 2026-07-22 09:24:23.673942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c20b28cd5d0a'
down_revision: Union[str, None] = '734b495994a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailman_held_emails',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gmail_message_id', name='uq_held_user_message')
    )
    op.create_index(op.f('ix_mailman_held_emails_released_at'), 'mailman_held_emails', ['released_at'], unique=False)
    op.create_index(op.f('ix_mailman_held_emails_user_id'), 'mailman_held_emails', ['user_id'], unique=False)
    op.create_table('mailman_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('delivery_mode', sa.String(length=32), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=True),
    sa.Column('custom_times', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_window_start', sa.String(length=5), nullable=False),
    sa.Column('active_window_end', sa.String(length=5), nullable=False),
    sa.Column('dnd_enabled', sa.Boolean(), nullable=False),
    sa.Column('dnd_start', sa.String(length=5), nullable=True),
    sa.Column('dnd_end', sa.String(length=5), nullable=True),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('composio_trigger_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailman_settings_user_id'), 'mailman_settings', ['user_id'], unique=True)
    op.create_table('mailman_vip_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailman_vip_rules_user_id'), 'mailman_vip_rules', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mailman_vip_rules_user_id'), table_name='mailman_vip_rules')
    op.drop_table('mailman_vip_rules')
    op.drop_index(op.f('ix_mailman_settings_user_id'), table_name='mailman_settings')
    op.drop_table('mailman_settings')
    op.drop_index(op.f('ix_mailman_held_emails_user_id'), table_name='mailman_held_emails')
    op.drop_index(op.f('ix_mailman_held_emails_released_at'), table_name='mailman_held_emails')
    op.drop_table('mailman_held_emails')
    # ### end Alembic commands ###
